Ng.ELapak.Web/Areas/Admin/Controllers/UserController.cs
using Ng.ELapak.Web.Areas.Admin.Models;
using Ng.ELapak.Web.Areas.Admin.Services;
using Ng.ELapak.Web.Domain.Db;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Linq;

namespace Ng.ELapak.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class UserController : BaseController
    {

        private readonly IUserService _userbotService;

        public UserController(AppDbContenxt appDbContenxt, ILogger<UserService> logger)
        {
            _userbotService = new UserService(appDbContenxt, logger);
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Detail(string id)
        {
            UserViewModel user = _userbotService.GetUser(id);
            return View(user);
        }

        public IActionResult GetDataUsers(DataTableParamModel param)
        {
            string headers = Request.Headers.ToString();
            return Json(new
            {
                iTotalRecords = _userbotService.Count(param),
                iTotalDisplayRecords = _userbotService.Count(param),
                aaData = _userbotService.GetUsers(param)
            });
        }

        public IActionResult Edit(string id)
        {
            UserViewModel user = _userbotService.GetUser(id);
            return View(user);
        }

        public IActionResult Add()
        {
            UserViewModel user = new UserViewModel();
            return View("Edit", user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(UserViewModel model)
        {
            if(model.Password != model.ConfirmPassword)
            {
                TempData["AlertError"] = "Wrong Password Confirmation, please check again";
                return View("Edit", model);
            }
            if (!ModelState.IsValid)
            {
                TempData["AlertError"] = string.Join(System.Environment.NewLine, ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));
                return View(model);
            }
            else
            {
                if (_userbotService.AddUser(model))
                {
                    TempData["AlertSuccess"] = "Edit User Success";
                    return Redirect("/Admin/User");
                }
                else
                {
                    TempData["AlertError"] = "Edit User Failed";
                    return Redirect("/Admin/User");
                }
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(UserViewModel model)
        {
            
            if (model.Password != model.ConfirmPassword)
            {
                TempData["AlertError"] = "Wrong Password Confirmation, please check again";
                return View("Edit", model);
            }
            if (!ModelState.IsValid)
            {
                TempData["AlertError"] = string.Join(System.Environment.NewLine, ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));
                return View(model);
            }
            else
            {
                if (_userbotService.AddUser(model))
                {
                    TempData["AlertSuccess"] = "Add User Success";
                    return Redirect("/Admin/User");
                }
                else
                {
                    TempData["AlertError"] = "Add User Failed";
                    return Redirect("/Admin/User");
                }
            }
        }

        public IActionResult Delete(string id)
        {
            if (_userbotService.DelUser(id))
            {
                TempData["AlertSuccess"] = "Delete User Success";
                //return RedirectToAction(nameof(Index));
                //return Redirect("/Admin/User");
                return Redirect("/Admin/User");
            }
            TempData["AlertError"] = "Delete User Failed";
            //return RedirectToAction(nameof(Index));
            return Redirect("/Admin/User");

        }
    }
}

Ng.ELapak.Web/Controllers/ChatHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ng.ELapak.Web.Domain.Db;
using Ng.ELapak.Web.Domain.Services;
using Ng.ELapak.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Ng.ELapak.Web.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ChatHistoryController : ControllerBase
    {
        private readonly ICronChatHistoryService _chatHistoryService;
        public ChatHistoryController(AppDbContenxt appDbContenxt, ILogger<CronChatHistoryService> logger, IOptions<KataConfigurationSetting> setting)
        {
            _chatHistoryService = new CronChatHistoryService(appDbContenxt, logger, setting);
        }

        [HttpPost("updatechathistory")]
        public async Task<IActionResult> UpdateChatHistory(UpdateChatHistoryModel model)
        {
            DateTime StartDate = DateTime.Parse(model.StartDate);
            DateTime EndDate = DateTime.Parse(model.EndtDate);
            int DayInterval = 1;

            List<DateTime> dateList = new List<DateTime>();
            while (StartDate.AddDays(DayInterval) <= EndDate)
            {
                StartDate = StartDate.AddDays(DayInterval);
                await _chatHistoryService.UpdateChatHistoryByPeriode(StartDate);
            }
            
            return Ok();
        }
    }
}

Ng.ELapak.Web/Controllers/ChatbotUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ng.ELapak.Web.Domain.Db;
using Ng.ELapak.Web.Domain.Services;
using Ng.ELapak.Web.Filters;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Ng.ELapak.Web.Models;
using Ng.ELapak.Web.Domain.Model;
using Ng.ELapak.Web.Extensions;
using Microsoft.Extensions.Logging;

namespace Ng.ELapak.Web.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ChatbotUserController : ControllerBase
    {
        private readonly IChatbotUserService _chatUserbotService;
        private readonly ResponseMessage _responseMessage;
        public ChatbotUserController(AppDbContenxt appDbContenxt, ILogger<ChatbotUserService> logger)
        {
            _chatUserbotService = new ChatbotUserService(appDbContenxt, logger);
            _responseMessage = new ResponseMessage();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost("checkstatus")]
        public async Task<IActionResult> CheckStatus(ApiBaseModel model)
        {
            
            if (!ModelState.IsValid)
            {
                _responseMessage.SetBadRequest(message: string.Join(Environment.NewLine, ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage)));
            }
            else
            {
                return Ok(await _chatUserbotService.CheckStatus(model));
            }
            return Ok(_responseMessage);
        }

        [HttpPost("savechatbotuser")]
        public async Task<IActionResult> SaveChatbotUser(ChatbotUserApiModel model)
        {
            if (!ModelState.IsValid)
            {
                _responseMessage.SetBadRequest(message: string.Join(Environment.NewLine, ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage)));
            }
            else
            {
                return Ok(await _chatUserbotService.SaveChatbotUser(model));
            }
            return Ok(_responseMessage);
        }

        [HttpPost("saverating")]
        public async Task<IActionResult> SaveRating(RatingUserApiModel model)
        {
            if (!ModelState.IsValid)
            {
                //_responseMessage.SetBadRequest(message: string.Join(Environment.NewLine, ModelState.Values
                //    .SelectMany(v => v.Errors)
                //    .Select(e => e.ErrorMessage)));
                _responseMessage.SetCustomCode(408, string.Join(Environment.NewLine, ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage)));
            }
            else
            {
                return Ok(await _chatUserbotService.SaveRating(model));
            }
            return Ok(_responseMessage);
        }

        [HttpPost("handover")]
        public async Task<IActionResult> HandOver(HandOverApiModel model)
        {
            if (!ModelState.IsValid)
            {
                _responseMessage.SetCustomCode(408, string.Join(Environment.NewLine, ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage)));
            }
            else
            {
                return Ok(await _chatUserbotService.HandOver(model));
            }
            return Ok(_responseMessage);
        }
    }
}

Ng.ELapak.Web/Areas/Admin/Views/Shared/_FlashMessage.cshtml
@if (TempData["AlertSuccess"] != null)
{
    string alertContent = (string)TempData["AlertSuccess"];

    <div class="alert alert-success">
        <button aria-hidden="true" data-dismiss="alert" class="close" type="button"></button>
        @alertContent
    </div>
}
@if (TempData["AlertError"] != null)
{
    string alertContent = (string)TempData["AlertError"];

    <div class="alert alert-danger">
        <button aria-hidden="true" data-dismiss="alert" class="close" type="button"></button>
        @alertContent
    </div>
}

Ng.ELapak.Web/Areas/Admin/Views/Shared/_Footer.cshtml
<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="page-footer-inner">
        2019 &copy; Chatbot.
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>
<!-- END FOOTER -->

Ng.ELapak.Web/Areas/Admin/Views/Shared/_Header.cshtml
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a href="index.html">
                <img src="~/assets/admin/img/logo.png" alt="logo" class="logo-default" />
            </a>
        </div>
        <div class="menu-toggler sidebar-toggler">
            <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
        </div>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
        </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <!-- BEGIN PAGE TOP -->
        <div class="page-top">
            <!-- BEGIN TOP NAVIGATION MENU -->
            <div class="top-menu">
                <ul class="nav navbar-nav pull-right">
                    <!-- BEGIN USER LOGIN DROPDOWN -->
                    <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                    <li class="dropdown dropdown-user dropdown-dark">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <span class="username username-hide-on-mobile">
                                Administrator
                            </span>
                            <!-- DOC: Do not remove below empty space(&nbsp;) as its purposely used -->
                            <img alt="" class="img-circle" src="~/Assets/admin/img/avatar11.jpg" />
                        </a>
                        <ul class="dropdown-menu dropdown-menu-default">
                            <li>
                                <a href="#" data-toggle="modal" data-target="#changePassword">
                                    <i class="icon-lock"></i> Change Password
                                </a>
                            </li>
                            <li>
                                <a href="authentication/logout">
                                    <i class="icon-key"></i> Log Out
                                </a>
                            </li>
                        </ul>
                    </li>
                    <!-- END USER LOGIN DROPDOWN -->
                </ul>
            </div>
            <!-- END TOP NAVIGATION MENU -->
        </div>
        <!-- END PAGE TOP -->
    </div>
    <!-- END HEADER INNER -->
</div>
<!-- END HEADER -->

Ng.ELapak.Web/Areas/Admin/Views/Shared/_Layout.cshtml
@using Ng.ELapak.Web.Extensions;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>@ViewData["Title"] - Ng.ELapak</title>
    <meta content="" name="description" />
    <base href='@Url.AbsoluteContent("~/")'>
    <meta content="" name="author" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="https://fonts.googleapis.com/css?family=Oxygen" rel="stylesheet">
    <link href="~/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="~/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css">
    <link href="~/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="~/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
    <link href="~/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <link href="~/assets/global/plugins/morris/morris.css" rel="stylesheet" type="text/css">
    <!-- BEGIN THEME STYLES -->
    <link href="~/assets/global/css/components-rounded.css" id="style_components" rel="stylesheet" type="text/css" />
    <link href="~/assets/global/css/plugins.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/admin/css/layout.css" rel="stylesheet" type="text/css" />
    <link id="style_color" href="~/assets/admin/css/themes/light.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/admin/css/custom.css" rel="stylesheet" type="text/css" />
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="favicon.ico" />
    @RenderSection("Styles", required: false)
</head>
<body class="page-header-fixed page-sidebar-fixed page-sidebar-closed-hide-logo">
    @{
        await Html.RenderPartialAsync("_Header");
    }
    <div class="page-container">
        <div class="page-sidebar-wrapper">
            @{
                await Html.RenderPartialAsync("_SideBar");
            }
        </div>
        <div class="page-content-wrapper">
            @RenderBody();
        </div>
    </div>
    @{
        await Html.RenderPartialAsync("_Footer");
    }
    <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
    <!-- BEGIN CORE PLUGINS -->
    <!--[if lt IE 9]>
    <script src="Assets/global/plugins/respond.min.js"></script>
    <script src="Assets/global/plugins/excanvas.min.js"></script>
    <![endif]-->
    <script src="~/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
    <!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
    <script src="~/assets/global/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>

    <script src="~/assets/global/scripts/metronic.js" type="text/javascript"></script>
    <script src="~/assets/admin/scripts/layout.js" type="text/javascript"></script>
    <script src="~/assets/admin/scripts/dashboard.js" type="text/javascript"></script>
    <script>
        jQuery(document).ready(function () {
            Metronic.init(); // init metronic core components
            Layout.init(); // init current layout
        });
        var baseUrl = document.baseURI;
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Ng.ELapak.Web/Areas/Admin/Views/Shared/_SideBar.cshtml
@using Ng.ELapak.Web.Extensions;
@{
    List<SiteMenu> ListMenu = new List<SiteMenu>();

    ListMenu.Add(new SiteMenu()
    {
        Id = "dashboard-index",
        Icon = "icon-home",
        Title = "Dashboard",
        Url = Url.Action("Index", "Dashboard"),
    });
    ListMenu.Add(new SiteMenu()
    {
        Id = "chatbotuser-index",
        Icon = "icon-users",
        Title = "Chatbot User",
        Url = Url.Action("Index", "ChatbotUser"),
    });
    //ListMenu.Add(new SiteMenu()
    //{
    //    Id = "chathistory-index",
    //    Icon = "icon-bubble",
    //    Title = "Chat FAQ History",
    //    Url = Url.Action("Index", "ChatHistory"),
    //});
     ListMenu.Add(new SiteMenu()
    {
        Id = "cmsproduct-index",
        Icon = "icon-user",
        Title = "Product",
        Url = Url.Action("Index", "Products"),
    });
    ListMenu.Add(new SiteMenu()
    {
        Id = "cmsuser-index",
        Icon = "icon-user",
        Title = "CMS User",
        Url = Url.Action("Index", "User"),
    });
    
    ListMenu.Add(new SiteMenu()
    {
        Id = "cmspurchase-index",
        Icon = "icon-user",
        Title = "Purchase Order",
        Url = Url.Action("PurchaseOrder", "Products"),
    });
}
<!-- END -->
<div class="page-sidebar navbar-collapse collapse">
    <!-- BEGIN SIDEBAR MENU -->
    <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
    <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
    <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
    <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <div class="page-sidebar-user">
        <img alt="" class="img-circle" src="~/Assets/admin/img/avatar11.jpg" />
        <span>Welcome, <b>Administrator</b></span>
    </div>
    <ul class="page-sidebar-menu " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
        @{
            foreach (var menu in ListMenu)
                {
                    <li class="@(ViewBag.ActiveMenu[0].Equals(menu.Id) && menu.ListSubmenu != null && menu.ListSubmenu.Count > 0 ? "open" : ViewBag.ActiveMenu[0].Equals(menu.Id) ? "active" : "")">
                            <a href="@(String.IsNullOrEmpty(menu.Url) ? "javascript:;" : @menu.Url)">
                                <i class="@menu.Icon"></i>
                                <span class="title">@menu.Title</span>
                                @if (menu.ListSubmenu != null && menu.ListSubmenu.Count > 0)
                                {
                                    <span class="arrow @(ViewBag.ActiveMenu[0].Equals(menu.Id) ? "open" : "")"></span>
                                }
                            </a>
                            @if (menu.ListSubmenu != null && menu.ListSubmenu.Count > 0)
                            {
                                <ul class="sub-menu" style="@(ViewBag.ActiveMenu[0].Equals(menu.Id) && ViewBag.ActiveMenu.Length > 1 ? "display: block;" : "")">
                                    @foreach (var submenu in menu.ListSubmenu)
                                    {
                                        <li class="@(ViewBag.ActiveMenu.Length > 1 && ViewBag.ActiveMenu[1].Equals(submenu.Id) ? "active" : "")">
                                            <a href="@(String.IsNullOrEmpty(submenu.Url) ? "javascript:;" : @submenu.Url)"><i class="@submenu.Icon"></i> @submenu.Title</a>
                                        </li>
                                    }
                                </ul>
                            }
                        </li>
                }
            }
        }
    </ul>
    <!-- END SIDEBAR MENU -->
</div>